#!/bin/sh
# Assumes this all lives in ~/bin/dotvim 

# -- Compiling vim --
# cd ~/code
# git clone git://github.com/b4winckler/vim.git
# cd vim
# git checkout -b vim73 origin/hg/vim73
# cd src
# ./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp --enable-perlinterp --enable-cscope --with-global-runtime=/usr/local/share/vim/vim73
# make

# -- Copy vim to ~/bin and runtime to /usr/local/share
# cp ./vim ~/bin
# cp -r ../runtime /usr/local/share/vim/vim73


rm -f ~/.vim
ln -s ~/bin/dotvim ~/.vim

rm -f ~/.vimrc
ln -s ~/bin/dotvim/vimrc ~/.vimrc

rm -f ~/.gvimrc
ln -s ~/bin/dotvim/gvimrc ~/.gvimrc
